EcommerceLeo/Areas/Admin/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EcommerceLeo.Domain.Entities;
using EcommerceLeo.Domain.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceLeo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriaController : Controller
    {
        private readonly ICategoriaRepository _categoriaRepository;

        public CategoriaController(ICategoriaRepository categoriaRepository)
        {
            _categoriaRepository = categoriaRepository;
        }
        public IActionResult Index()
        {
            var cg = _categoriaRepository.GetAllCategoria();
            return View(cg);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CategoriaProduto catg)
        {
            try
            {
                var cg = _categoriaRepository.InsertCategoria(catg.nmCategoria);
                ModelState.Clear();

                return View();

            }
            catch (Exception ex)
            {
                var message = $"Generic Error: {ex.Message}";
                ViewBag.B = message;
                return View();
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var cg = _categoriaRepository.GetCategoriaId(id);
            
            return PartialView("_Edit", cg);
        }

        [HttpPost]
        public IActionResult Edit(int id, CategoriaProduto ctg)
        {
            var cg = _categoriaRepository.UpdateCategoria(ctg.idCategoria, ctg.nmCategoria);
            return PartialView("_Edit", cg);
        }

        [HttpDelete]
        public void DeleteCategoria(int id)
        {
            _categoriaRepository.DeleteCategoria(id);
        }
    }
}

EcommerceLeo/Areas/Admin/Controllers/CupomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EcommerceLeo.Domain.Entities;
using EcommerceLeo.Domain.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace EcommerceLeo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CupomController : Controller
    {
        private readonly ICupomRepository _cupomRepository;

        public CupomController(ICupomRepository cupomRepository)
        {
            _cupomRepository = cupomRepository;
        }
        public IActionResult Index()
        {
            var cup = _cupomRepository.GetAllCupom();
            return View(cup);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cupom cupom)
        {
            try
            {
                var cup = _cupomRepository.CreateCupom(cupom.TipoCupom, cupom.CodigoCupom, cupom.ValorDesconto);
                ModelState.Clear();
                return View();
            }
            catch (Exception ex)
            {

                var message = $"Generic Error: {ex.Message}";
                ViewBag.B = message;
                return View();
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var cup = _cupomRepository.SearchCupomId(id);
            ViewBag.Edit = cup;
            return PartialView("_Edit",cup);
        }

        [HttpPost]
        public IActionResult Edit(int id, Cupom cupom)
        {
            var cup = _cupomRepository.EditCupom(cupom.IdCupom,cupom.TipoCupom,cupom.CodigoCupom,cupom.ValorDesconto);
            return PartialView("_Edit",cup);
        }

        [HttpDelete]
        public void DeleteCupom(int id)
        {
            _cupomRepository.DeleteCupom(id);
        }
    }
}

EcommerceLeo/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EcommerceLeo.Domain.Entities;
using EcommerceLeo.Domain.Repositories.Interfaces;
using EcommerceLeo.Web.Utils;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EcommerceLeo.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;

        public ProdutoController(IProdutoRepository produtoRepository)
        {         
            _produtoRepository = produtoRepository;
        }

        // GET: /<controller>/
        public IActionResult Detalhe(int id)
        {
            var produto = _produtoRepository.GetProdutoById(id);
            return View(produto);
        }

        [HttpPost]
        [ActionName("Detalhe")]
        public ActionResult AddToCart(int id)
        {
            List<Produto> produtos = new List<Produto>();

            var produto = _produtoRepository.GetProdutoById(id);

            produtos = HttpContext.Session.Get<List<Produto>>("produtos");
            if (produtos == null)
            {
                produtos = new List<Produto>();
            }

            int qtdeItensParaAdicionarNoCarrinho = 3;

            if(qtdeItensParaAdicionarNoCarrinho > 1) 
            {
                for (int i = 0; i < qtdeItensParaAdicionarNoCarrinho; i++)
                {
                    produtos.Add(produto);
                }
            }
            else
            {
                produtos.Add(produto);
            }
            
            HttpContext.Session.Set("produtos", produtos);

            return View(produto);

        }


    }
}

EcommerceLeo/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/Admin/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Admin/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          asp-fallback-href="~/Admin/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/Admin/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApplication1</a>
            </div>
            
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <div class="user-panel">
                            <div class="pull-left image">
                                <img src="~/img/blog-thumbs/1.jpg" class="img-circle" alt="User Image">
                            </div>
                            <div class="pull-left info">
                                <p>Krauser</p>
                                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                            </div>
                        </div>
                    </li>
                    <li><a asp-area="Admin" asp-controller="Produto" asp-action="Index">Produto</a></li>
                    <li><a asp-area="Admin" asp-controller="Cupom" asp-action="Index">Cupom</a></li>
                    <li><a asp-area="Admin" asp-controller="Categoria" asp-action="Index">Categoria Produto</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Sair</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script src="~/Admin/lib/jquery/dist/jquery.js"></script>
    <script src="~/Admin/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/Admin/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/Admin/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
            asp-fallback-src="~/Admin/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
    </script>
    <script src="~/Admin/js/site.min.js" asp-append-version="true"></script>
</body>
</html>